<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Fraud PHP is a website template that allows you to create one page apps with PHP by imitating Next.js">
    <meta name="keywords" content="fraud php, php, one page app, php website template, free">
    <meta name="author" content="therenaydin">
    <link rel="stylesheet" href="/src/css/main.css">
    <link rel="stylesheet" href="/src/css/utils.css">
    <link rel="shortcut icon" href="/src/imgs/static/content/favicon.svg" type="image/x-icon">
    <script src="/src/js/plugins/jquery.js"></script>
    <title>Create one page apps - Fraud PHP</title>
</head>

<body id="_fraud">
    <main id="App">
        <!----Page Content Goes Here DO NOT EDIT THIS FILE---->
    </main>
    <script type="module" src="/_fraud/js/core.js"></script>
</body>

</html>